server:
  port: 8180 # mapstruct 端口号
spring:
  datasource:
    url: jdbc:mysql://www.muzaijian.cn:3307/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai # Mysql Url
    username: mall # Mysql 账号
    password: mall # Mysql 密码
  druid:
    initial-size: 5 # 连接池初始化大小
    min-idle: 10 # 最小空闲连接数
    max-active: 20 # 最大连接数
    web-stat-filter:
      exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" # 不统计这些请求数据
    stat-view-servlet:
      login-username: druid # 监控网页用户名
      login-password: druid # 监控网页密码
mybatis-plus:
  mapper-locations: # Mybatis Plus 扫描 xml 文件路径
    - classpath:dao/*.xml
    - classpath*:cn/**/mapper/*.xml